In [2]:
import geopandas as gpd
from shapely.geometry import Polygon

# 创建示例数据，使用自定义坐标
data = [
    {"type": "Feature", "properties": {"id": 1, "type": "residential"}, "geometry": {"type": "Polygon", "coordinates": [[[0, 0], [4, 0], [4, 3], [0, 3], [0, 0]]]}},
    {"type": "Feature", "properties": {"id": 2, "type": "business"}, "geometry": {"type": "Polygon", "coordinates": [[[5, 5], [10, 5], [10, 8], [5, 8], [5, 5]]]}}
]

# 将数据转换为GeoDataFrame
gdf = gpd.GeoDataFrame.from_features(data)

#gdf.set_crs(epsg=4326, inplace=True)

# 打印GeoDataFrame
print(gdf)

# 计算每个地块的面积
gdf['area'] = gdf.geometry.area

# 打印带有面积的GeoDataFrame
print(gdf[['id', 'type', 'area']])

                                            geometry  id         type
0  POLYGON ((0.00000 0.00000, 4.00000 0.00000, 4....   1  residential
1  POLYGON ((5.00000 5.00000, 10.00000 5.00000, 1...   2     business
   id         type  area
0   1  residential  12.0
1   2     business  15.0

In [4]:
import geopandas as gpd
from shapely.geometry import LineString

# 创建示例数据
data = [
    {"geometry": LineString([(1000, 1000), (500, 1000)])},
    {"geometry": LineString([(500, 1000), (1000, 1000)])},
    {"geometry": LineString([(2000, 2000), (1500, 2000)])}
]

# 将数据转换为GeoDataFrame
gdf = gpd.GeoDataFrame(data)

In [5]:
gdf.head()

                                            geometry
0   LINESTRING (1000.000 1000.000, 500.000 1000.000)
1   LINESTRING (500.000 1000.000, 1000.000 1000.000)
2  LINESTRING (2000.000 2000.000, 1500.000 2000.000)

In [6]:
gdf = gdf.drop_duplicates()

In [7]:
gdf.head()

                                            geometry
0   LINESTRING (1000.000 1000.000, 500.000 1000.000)
1   LINESTRING (500.000 1000.000, 1000.000 1000.000)
2  LINESTRING (2000.000 2000.000, 1500.000 2000.000)

In [8]:


# 定义一个函数来规范化LineString
def normalize_linestring(ls):
    coords = list(ls.coords)
    return LineString(coords) if coords[0] < coords[-1] else LineString(coords[::-1])

# 应用规范化函数
gdf['normalized_geometry'] = gdf['geometry'].apply(normalize_linestring)

# 删除重复的LineString
gdf = gdf.drop_duplicates(subset='normalized_geometry')

# 删除辅助列
gdf = gdf.drop(columns='normalized_geometry')

print(gdf)

                                            geometry
0   LINESTRING (1000.000 1000.000, 500.000 1000.000)
2  LINESTRING (2000.000 2000.000, 1500.000 2000.000)

In [11]:
import pickle
p=pickle.load(open('init_plan_grid3.pickle','rb'))
print(p)

{'gdf':     id  type  existence                                           geometry
0    1    13       True                                POINT (0.000 0.000)
1    2    13       True                             POINT (1000.000 0.000)
2    3    13       True                          POINT (1000.000 1000.000)
3    4    13       True                             POINT (0.000 1000.000)
4    9     1       True  POLYGON ((0.000 0.000, 1000.000 0.000, 1000.00...
5   12    13       True                          POINT (1000.000 2000.000)
6   13    13       True                             POINT (0.000 2000.000)
7   18     1       True  POLYGON ((0.000 1000.000, 1000.000 1000.000, 1...
8   20    13       True                             POINT (2000.000 0.000)
9   21    13       True                          POINT (2000.000 1000.000)
10  27     1       True  POLYGON ((1000.000 0.000, 2000.000 0.000, 2000...
11  30    13       True                          POINT (2000.000 2000.000)
12  36     1       True  POLYGON ((1000.000 1000.000, 2000.000 1000.000...
13   5     2       True           LINESTRING (0.000 0.000, 1000.000 0.000)
14   6     2       True     LINESTRING (1000.000 0.000, 1000.000 1000.000)
15   7     2       True     LINESTRING (1000.000 1000.000, 0.000 1000.000)
16   8     2       True           LINESTRING (0.000 1000.000, 0.000 0.000)
17  15     2       True  LINESTRING (1000.000 1000.000, 1000.000 2000.000)
18  16     2       True     LINESTRING (1000.000 2000.000, 0.000 2000.000)
19  17     2       True        LINESTRING (0.000 2000.000, 0.000 1000.000)
20  23     2       True        LINESTRING (1000.000 0.000, 2000.000 0.000)
21  24     2       True     LINESTRING (2000.000 0.000, 2000.000 1000.000)
22  25     2       True  LINESTRING (2000.000 1000.000, 1000.000 1000.000)
23  33     2       True  LINESTRING (2000.000 1000.000, 2000.000 2000.000)
24  34     2       True  LINESTRING (2000.000 2000.000, 1000.000 2000.000)}